# Default values for tf-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Replicas of tf-operator deployment.
replicas: 1

# Controller configurations.
controller:
  # -- Number of workers for controller.
  workers: 10
  # -- Client connection configurations.
  clientConnection:
    # -- QPS is the number of queries per second allowed for K8S api server connection.
    qps: 10
    # --  Burst allows extra queries to accumulate when a client is exceeding its rate.
    burst: 30

# -- Liveness probe configuration.
# The operator pod will be restarted if the liveness probe fails.
livenessProbe:
  # -- Number of seconds after the container has started before liveness probes are initiated.
  initialDelaySeconds: 15
  # -- How often (in seconds) to perform the probe.
  periodSeconds: 30
  # -- Number of seconds after which the probe times out.
  timeoutSeconds: 3
  # -- Minimum consecutive failures for the probe to be considered failed.
  failureThreshold: 3

# -- Readiness probe configuration.
# The operator pod will not receive traffic if the readiness probe fails.
readinessProbe:
  # -- Number of seconds after the container has started before readiness probes are initiated.
  initialDelaySeconds: 10
  # -- How often (in seconds) to perform the probe.
  periodSeconds: 15
  # -- Number of seconds after which the probe times out.
  timeoutSeconds: 3
  # -- Minimum consecutive failures for the probe to be considered failed.
  failureThreshold: 3
