apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-job-operator
  namespace: {{ .Release.Namespace }}
  labels:
    kustomize.component: tf-job-operator
    {{- include "arena.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      kustomize.component: tf-job-operator
      {{- include "arena.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        kustomize.component: tf-job-operator
        name: tf-job-operator
        {{- include "arena.labels" . | nindent 8 }}
    spec:
      containers:
      - name: tf-job-operator
        image: {{ include "arena.imagePrefix" . }}/{{ .Values.image }}:{{ .Values.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
        - /opt/kubeflow/tf-operator.v1
        - --alsologtostderr
        - -v=1
        - --monitoring-port=8443
        - --threadiness={{ .Values.controller.workers }}
        - --qps={{ .Values.controller.clientConnection.qps }}
        - --burst={{ .Values.controller.clientConnection.burst }}
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8443
          name: monitoring-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /metrics
            port: monitoring-port
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /metrics
            port: monitoring-port
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config-volume
        configMap:
          name: tf-job-operator-config
      nodeSelector:
        {{- include "arena.nodeSelector" . | nindent 8 }}
        {{- include "arena.nonEdgeNodeSelector" . | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  kustomize.component: tf-job-operator
                  {{- include "arena.labels" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
      tolerations:
      {{- with .Values.global.tolerations }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      {{- with .Values.tolerations }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      {{- include "arena.tolerateNonEdgeNodeSelector" . | nindent 6 }}
      serviceAccountName: tf-job-operator
